/**
 * Help Content Database
 *
 * Pre-written explanations for all major concepts in the dashboard
 * with 3-level explanations (Beginner, Intermediate, Expert)
 */

import { HelpContent } from '../components/education/SmartHelpPanel';

export const HELP_CONTENT_DATABASE: Record<string, HelpContent> = {
  'energy-mix': {
    id: 'energy-mix',
    title: 'Energy Mix',
    category: 'Basics',
    explanations: {
      beginner: `Energy Mix shows where our electricity comes from! Think of it like a recipe - instead of ingredients like flour and sugar, we use different "ingredients" to make electricity:

🌬️ Wind turbines (using wind)
☀️ Solar panels (using sunlight)
💧 Hydro dams (using flowing water)
⚡ Natural gas plants (burning gas)
⚛️ Nuclear plants (splitting atoms)

Just like a recipe, the mix changes throughout the day! At night, we can't use solar, so we use more of the other sources. A good energy mix uses lots of clean, renewable sources like wind and solar!`,

      intermediate: `The Energy Mix represents the proportion of electricity generated by different sources in real-time. It's measured in:

• Megawatts (MW) - How much power right now
• Percentage (%) - What share of total generation

Key types of energy sources:
🟢 Renewables (Clean): Wind, Solar, Hydro - Don't run out, low carbon
🟡 Fossil Fuels: Natural Gas, Coal - Limited supply, high carbon
🔵 Nuclear: Uranium - Clean but creates waste

A balanced mix considers:
- Reliability (baseload vs. intermittent)
- Cost ($/MWh)
- Environmental impact (CO2 emissions)
- Energy security (domestic vs. imported)`,

      expert: `Energy Mix Analysis provides real-time generation capacity data from grid operators (AESO, IESO, BC Hydro) via API integration:

Technical Breakdown:
• Baseload: Nuclear (90%+ capacity factor), Run-of-river Hydro
• Load Following: Natural Gas Combined Cycle, Hydro Storage
• Peaking: Gas Turbines, Battery Storage
• Variable Renewable: Wind (35% CF), Solar (25% CF)

Grid Dispatch Stack:
1. Must-run generators (nuclear, renewables)
2. Economic dispatch order by marginal cost
3. Ancillary services (frequency regulation, reserves)
4. Curtailment during low demand

Key Metrics:
- Capacity Factor = Actual Generation / Nameplate Capacity
- Emissions Intensity = gCO2/kWh (varies by source)
- LCOE (Levelized Cost) = Total lifecycle cost / Total energy
- Grid Stability = Frequency variance, voltage control

Integration challenges with high renewable penetration:
- Duck curve (California) - Evening ramp-up challenges
- Grid inertia reduction - Requires synthetic inertia or storage
- Transmission constraints - Regional interconnection limits`
    },
    realWorldExample: `Imagine your home in the evening. When you turn on lights, TV, and start cooking dinner, you're part of the "peak demand" time (5-9 PM).

During this time, Alberta might use:
- 60% Natural Gas (reliable, quick to turn on/off)
- 20% Wind (if it's windy!)
- 15% Coal (being phased out)
- 5% Other sources

But at 2 AM when everyone's asleep? Demand drops 40%, so we use fewer power plants. This is why understanding the mix helps - we can plan when to charge electric cars or run dishwashers to use cheaper, cleaner electricity!`,
    funFact: `🌟 Did you know? On a really windy day in Alberta, wind turbines can generate enough power for over 1 million homes! That's like powering the entire cities of Calgary and Edmonton combined - just from wind!`,
    keyTakeaways: [
      'Energy mix changes throughout the day based on demand',
      'Renewable sources (wind, solar, hydro) are clean but variable',
      'A diverse mix ensures reliability and lower costs',
      'Canada is moving toward more renewable energy to fight climate change'
    ],
    relatedConcepts: [
      { id: 'renewable-energy', title: 'What is Renewable Energy?' },
      { id: 'grid-stability', title: 'How the Power Grid Works' },
      { id: 'capacity-factor', title: 'Understanding Capacity Factor' },
      { id: 'carbon-emissions', title: 'Carbon Emissions from Energy' }
    ]
  },

  'renewable-energy': {
    id: 'renewable-energy',
    title: 'Renewable Energy',
    category: 'Clean Energy',
    explanations: {
      beginner: `Renewable energy comes from sources that never run out! Unlike coal or oil that will eventually be used up, renewable sources keep coming back naturally.

The main types are:

🌬️ **Wind** - Giant turbines spin in the wind, like huge pinwheels
☀️ **Solar** - Panels capture sunlight and turn it into electricity
💧 **Hydro** - Water flowing through dams spins turbines
🌊 **Tidal** - Ocean waves and tides generate power
🌋 **Geothermal** - Heat from inside Earth

Why they're awesome:
✅ Never run out
✅ Don't pollute the air
✅ Help fight climate change
✅ Create jobs
✅ Costs keep going down`,

      intermediate: `Renewable energy sources generate electricity without depleting natural resources or producing significant greenhouse gas emissions during operation.

**Key Characteristics:**
- Naturally Replenishing: Source regenerates on human timescales
- Low Carbon: Minimal CO2 emissions during operation
- Variable Output: Most depend on weather conditions (except hydro/geothermal)
- Decreasing Costs: Technology improvements driving price down

**Economics:**
- Wind: $30-60/MWh (cheapest new generation)
- Solar: $30-50/MWh (falling rapidly)
- Hydro: $40-100/MWh (established, location-dependent)
- For comparison: Gas $40-80/MWh, Coal $60-140/MWh

**Challenges:**
- Intermittency: Need backup power or storage
- Grid Integration: Requires flexible, smart grid infrastructure
- Location-Specific: Best resources aren't always near cities
- Upfront Costs: High capital expense, low operating costs`,

      expert: `Renewable Energy Systems (RES) encompass non-depleting, low-emission generation technologies with distinct technical characteristics:

**Resource Assessment:**
- Wind: Weibull distribution analysis, capacity factor 25-45% (offshore 35-50%)
- Solar PV: Global Horizontal Irradiance (GHI), Performance Ratio typically 75-85%
- Hydro: Run-of-river (CF 40-70%) vs. Storage (CF 40-60%, flexible dispatch)
- Geothermal: Baseload (CF 85-95%), binary cycle for low-temp resources

**Grid Integration Technical Challenges:**

1. Variability & Uncertainty:
   - Sub-hourly forecasting (machine learning, ensemble methods)
   - Probabilistic dispatch optimization
   - Reserve requirement increases (regulation, load following)

2. Reduced System Inertia:
   - Grid-forming inverters (GFM) vs. grid-following (GFL)
   - Synthetic inertia from battery storage or wind turbines
   - Fast frequency response (FFR) ancillary services

3. Transmission & Distribution:
   - Power flow reversal in distribution networks
   - Voltage control with high DER penetration
   - Reactive power management (Q-V droop control)

**Energy Storage Integration:**
- Li-ion batteries: 4-6 hour duration, rapid response (<100ms)
- Pumped hydro: 8-24+ hours, bulk storage
- Green hydrogen: Seasonal storage, sector coupling

**Market & Policy Mechanisms:**
- Feed-in Tariffs (FIT) vs. Renewable Portfolio Standards (RPS)
- Renewable Energy Certificates (RECs) / Carbon Credits
- Capacity markets with technology-neutral auctions
- Net metering and time-of-use rates

**LCOE Calculation:**
LCOE = (Capital Cost + O&M + Financing) / Lifetime Energy Production
- Consider: capacity factor, degradation, financing terms
- Competing with "Energy Value" not just cost
- System LCOE includes integration costs`
    },
    realWorldExample: `Let's look at a real Canadian community: Summerside, Prince Edward Island.

This town of 16,000 people gets 100% of its electricity from renewable sources! They use:
- Wind turbines on nearby farms
- Solar panels on municipal buildings
- Battery storage to balance supply

Result?
✅ Electricity bills down 10-20%
✅ No more power outages from storms (battery backup)
✅ Created 300 local jobs
✅ Reduced emissions by 40,000 tonnes/year (like removing 8,000 cars)

What started as an expensive experiment is now saving money AND the environment!`,
    funFact: `🚀 In 2023, renewables became the CHEAPEST form of new electricity generation in history! Solar and wind are now cheaper than coal and gas, even without subsidies. That's why investors are pouring money into clean energy - it's good for the planet AND their wallets!`,
    keyTakeaways: [
      'Renewable energy is now the cheapest form of new power generation',
      'Main challenge is intermittency (wind doesn\'t always blow, sun doesn\'t always shine)',
      'Battery storage is solving the intermittency problem',
      'Canada has incredible renewable resources: hydro, wind, solar, geothermal',
      'Transitioning to renewables creates jobs and reduces pollution'
    ],
    relatedConcepts: [
      { id: 'energy-storage', title: 'Energy Storage & Batteries' },
      { id: 'smart-grid', title: 'Smart Grid Technology' },
      { id: 'carbon-emissions', title: 'Reducing Carbon Emissions' },
      { id: 'energy-costs', title: 'Cost of Different Energy Sources' }
    ]
  },

  'carbon-emissions': {
    id: 'carbon-emissions',
    title: 'Carbon Emissions',
    category: 'Environment',
    explanations: {
      beginner: `Carbon emissions are like "invisible smoke" that comes from burning fossil fuels (coal, oil, natural gas) to make electricity, drive cars, or heat homes.

🏭 Why it matters:
Carbon dioxide (CO2) traps heat in Earth's atmosphere like a blanket, making the planet warmer. This causes:
- Hotter summers
- Melting ice caps
- Rising sea levels
- More extreme weather

🌱 How we measure it:
- Tons of CO2 per year
- Grams of CO2 per kilowatt-hour of electricity

Different energy sources produce different amounts:
🔴 Coal: LOTS of carbon (most polluting)
🟡 Natural Gas: Medium carbon
🟢 Wind/Solar/Hydro: ZERO carbon (clean!)

🎯 The Goal:
Reduce carbon emissions to "Net Zero" by 2050 to stop climate change!`,

      intermediate: `Carbon emissions from electricity generation are measured in grams of CO2 equivalent per kilowatt-hour (gCO2e/kWh). This includes:

**Emission Intensities by Source:**
☠️ Coal: 820-950 gCO2/kWh (worst)
🟡 Natural Gas: 350-490 gCO2/kWh
🔵 Nuclear: 12-15 gCO2/kWh (lifecycle emissions)
🟢 Wind: 11-12 gCO2/kWh
🟢 Solar: 40-50 gCO2/kWh
🟢 Hydro: 24-30 gCO2/kWh

**Why It Varies:**
- Fuel quality (e.g., anthracite vs. lignite coal)
- Plant efficiency (modern CCGT vs. old gas plants)
- Manufacturing emissions (solar panel production)
- Lifecycle analysis (construction, operation, decommissioning)

**Carbon Pricing:**
Canada's carbon tax: $80/tonne CO2 (2024), rising to $170/tonne (2030)
- Makes fossil fuels more expensive
- Incentivizes clean energy
- Rebates to households

**Personal Carbon Footprint:**
Average Canadian: 15 tonnes CO2/year
- Electricity: ~2 tonnes
- Transportation: ~5 tonnes
- Heating: ~3 tonnes
- Everything else: ~5 tonnes`,

      expert: `Carbon Intensity Analysis for Power Systems:

**Emission Accounting Methodologies:**

1. **Direct Emissions (Scope 1):**
   - Combustion: C_emissions = Fuel_burned × Emission_factor × (1 - capture_rate)
   - Natural Gas CCGT: 350-400 gCO2/kWh (50-60% thermal efficiency)
   - Subcritical Coal: 900-1000 gCO2/kWh (33-38% efficiency)
   - Supercritical Coal: 750-850 gCO2/kWh (40-45% efficiency)

2. **Lifecycle Emissions (Scope 1-3):**
   - Includes: Manufacturing, construction, O&M, fuel extraction, decommissioning
   - IPCC Lifecycle Assessment values:
     - Wind: 11 gCO2e/kWh (steel, concrete in turbine/foundation)
     - Solar PV: 40-50 gCO2e/kWh (silicon purification, panel production)
     - Nuclear: 12 gCO2e/kWh (enrichment, construction, waste management)
     - Hydro: 24 gCO2e/kWh (reservoir methane in some cases)

**Grid Carbon Intensity Calculation:**

Marginal Emission Rate = dEmissions/dDemand
Average Emission Rate = Total Emissions / Total Generation

- Marginal rate determines impact of load changes
- Important for EV charging optimization, demand response

**Carbon Capture Utilization & Storage (CCUS):**
- Post-combustion capture: 85-90% capture rate, 15-25% energy penalty
- Pre-combustion (IGCC): 90-95% capture, better efficiency
- Oxy-fuel combustion: 90%+ capture, requires oxygen separation
- Storage: Geological sequestration, enhanced oil recovery (EOR)
- Cost: $50-100/tonne CO2 captured (decreasing)

**Decarbonization Pathways:**

1. **Supply-Side:**
   - Renewable generation build-out (70-85% of mix)
   - Nuclear baseload (10-20%)
   - CCS for remaining fossil (5-10%)
   - Green hydrogen for storage/backup

2. **Demand-Side:**
   - Electrification (transport, heating)
   - Energy efficiency improvements
   - Demand response / flexible loads
   - Behavioral changes

**Carbon Pricing Economics:**
- Social Cost of Carbon: $50-200/tonne (wide range, discount rate dependent)
- Carbon tax vs. Cap-and-Trade tradeoffs
- Border Carbon Adjustments (BCAs) to prevent leakage
- Revenue recycling: Dividends vs. investment in clean tech

**Net-Zero Targets:**
- Canada: 2050 net-zero legislation
- Interim targets: 40-45% below 2005 levels by 2030
- Electricity grid: 100% zero-emission by 2035
- Residual emissions offset with negative emission technologies (NET):
  - Direct Air Capture (DAC): $100-600/tonne
  - Bioenergy with CCS (BECCS)
  - Afforestation/reforestation`
    },
    realWorldExample: `Let's compare two provinces:

**Alberta (High Carbon):**
- 90% electricity from fossil fuels (mostly coal & gas)
- Grid carbon intensity: ~600 gCO2/kWh
- Average household: 10,000 kWh/year = 6 tonnes CO2
- Like driving a gas car 24,000 km

**Quebec (Low Carbon):**
- 95% electricity from hydro
- Grid carbon intensity: ~30 gCO2/kWh
- Same household: 10,000 kWh/year = 0.3 tonnes CO2
- 20x cleaner than Alberta!

**Your Impact:**
If an Alberta family switched to an electric car:
- Save: 3 tonnes CO2/year
- BUT charging from coal/gas grid adds 2 tonnes
- Net benefit: 1 tonne/year

Same family in Quebec:
- Save: 3 tonnes CO2/year
- EV charging adds only 0.1 tonnes
- Net benefit: 2.9 tonnes/year

**This is why grid decarbonization matters so much!**`,
    funFact: `🌍 Mind-blowing fact: The entire internet and all data centers globally produce about 2% of world's carbon emissions - roughly the same as the aviation industry! That's why tech companies like Google and Microsoft are investing billions in renewable energy to power their servers.`,
    keyTakeaways: [
      'Carbon emissions from energy cause climate change',
      'Different energy sources have vastly different carbon intensities',
      'Coal is ~25x more polluting than renewable energy',
      'Canada is phasing out coal by 2030',
      'Personal actions matter: energy efficiency, EVs, clean energy choices',
      'Carbon pricing makes clean energy more economically competitive'
    ],
    relatedConcepts: [
      { id: 'renewable-energy', title: 'Renewable Energy' },
      { id: 'energy-mix', title: 'Energy Mix' },
      { id: 'climate-change', title: 'Climate Change Impacts' },
      { id: 'carbon-capture', title: 'Carbon Capture Technology' }
    ]
  },

  // Add more content entries as needed...
  'capacity-factor': {
    id: 'capacity-factor',
    title: 'Capacity Factor',
    category: 'Technical Metrics',
    explanations: {
      beginner: `Capacity Factor shows how often a power plant is actually running at full power.

Think of it like a store:
🏪 A 24/7 store that's always open = 100% capacity factor
🏪 A store open 12 hours/day = 50% capacity factor

For power plants:
⚛️ Nuclear: ~90% (runs almost all the time)
💧 Hydro: ~50% (depends on water flow)
🌬️ Wind: ~35% (only when it's windy)
☀️ Solar: ~25% (only during daytime, best when sunny)

Why it matters:
- Higher capacity = more reliable
- Lower capacity = need backup power
- Affects the cost per kWh
- Important for planning the grid`,

      intermediate: `Capacity Factor = (Actual Energy Generated / Maximum Possible Generation) × 100%

It measures how efficiently a power plant operates over a period (usually annually).

**Typical Values:**
- Nuclear: 85-95% (excellent baseload, planned maintenance only)
- Coal: 40-70% (economic dispatch, being phased out)
- Natural Gas CCGT: 40-65% (flexible, used for load following)
- Hydro (storage): 40-60% (seasonal variations, drought impacts)
- Onshore Wind: 30-45% (best sites in Alberta, Saskatchewan)
- Offshore Wind: 40-55% (steadier ocean winds)
- Solar PV: 15-30% (latitude dependent, weather variations)
- Geothermal: 85-95% (baseload, very reliable)

**Why Low Capacity Factors Aren't Always Bad:**
- Peaker plants (gas turbines): 5-20% CF, but essential for reliability
- Solar might be 20% CF but generates during peak demand (valuable!)
- Cost per kWh matters more than CF alone

**Impact on Economics:**
LCOE = (Capital + O&M) / (Capacity × CF × Lifetime)
Lower CF = Higher LCOE (more expensive per kWh)`,

      expert: `Capacity Factor Analysis & Grid Planning:

**Mathematical Definition:**
CF = E_actual / (P_nameplate × 8760 hours) × 100%

Where:
- E_actual = Annual energy generation (MWh)
- P_nameplate = Rated capacity (MW)
- 8760 = hours in a year (365 days × 24 hours)

**Factors Affecting Capacity Factor:**

1. **Resource Availability:**
   - Wind: Weibull distribution, power curve, wake effects
   - Solar: Solar irradiance (GHI/DNI), temperature coefficient
   - Hydro: Inflow variability, reservoir management strategy

2. **Technical Limitations:**
   - Forced outage rate (FOR): Unplanned shutdowns
   - Planned outage rate (POR): Scheduled maintenance
   - Deration: Partial output due to fouling, aging
   - Curtailment: Grid operator constraints, negative pricing

3. **Economic Dispatch:**
   - Merit order: Marginal cost determines dispatch priority
   - Gas plants: Flexible, run when economical
   - Coal: Ramping constraints, minimum stable output

**Advanced Metrics:**

1. **Equivalent Availability Factor (EAF):**
   EAF = (Available Hours - Equivalent Outage Hours) / Total Hours
   - Better indicator of reliability than CF
   - Accounts for partial outages

2. **Equivalent Forced Outage Rate (EFOR):**
   EFOR = (Forced Outage Hours + Equivalent Forced Derated Hours) / Service Hours
   - Key metric for baseload plants
   - Industry benchmark: Nuclear <5%, Fossil 5-10%

3. **Net Capacity Factor:**
   Accounts for parasitic load (station use, auxiliary power)
   - Important for CCUS plants (energy penalty for capture)

**Grid Planning Implications:**

1. **Resource Adequacy:**
   - Effective Load Carrying Capacity (ELCC) of variable renewables
   - ELCC_wind ≈ 10-20% of nameplate (contribution to peak)
   - ELCC_solar ≈ 40-70% (better correlation with peak demand)

2. **Capacity Credit:**
   Credit = ELCC / Nameplate Capacity
   - Used in capacity markets
   - Reflects reliability contribution, not energy

3. **Intermittency Management:**
   - Variability: Short-term fluctuations (sub-hourly)
   - Uncertainty: Forecast error (day-ahead to real-time)
   - Geographic diversity reduces correlation
   - Hybrid plants (wind + solar + storage) improve CF

**Optimization Strategies:**

1. **Improving Wind CF:**
   - Taller towers: Access higher, steadier winds (+5-10% CF)
   - Larger rotors: Better low-wind performance
   - Advanced controls: Yaw optimization, wake steering

2. **Improving Solar CF:**
   - Single-axis trackers: +20-30% vs. fixed tilt
   - Bifacial modules: +10-20% from ground reflectance
   - Hybrid inverters: DC overbuilding (1.2-1.4x)

3. **Storage-Enhanced CF:**
   - Solar + battery: Shift generation to peak demand
   - "Firm" renewable profile (90%+ CF equivalent)
   - Increased capacity credit (70-90%)`
    },
    realWorldExample: `Let's visit the Darlington Nuclear Station in Ontario:

**The Numbers:**
- Capacity: 3,512 MW (4 reactors × 878 MW)
- Capacity Factor: 93% (2022)
- Hours in a year: 8,760

**Calculation:**
Maximum possible generation = 3,512 MW × 8,760 hours = 30.8 million MWh
Actual generation = 30.8 million × 0.93 = 28.6 million MWh

**What does 28.6 million MWh power?**
Average Ontario home uses 9,000 kWh/year
28.6 billion kWh ÷ 9,000 = 3.2 million homes!

That's nearly HALF of all homes in Ontario powered by just this one station, running 93% of the time!

**Why 93% and not 100%?**
- 3-4 weeks/year for refueling each reactor (staggered)
- Routine maintenance
- Safety inspections
- Still incredibly reliable!`,
    funFact: `⚡ The worst capacity factor ever? Germany's solar panels during January! They average just 5-8% capacity factor in winter (short days, cloudy weather). But in summer? They jump to 30-35%! This is why energy storage and diverse renewable sources are so important - you can't rely on just one technology.`,
    keyTakeaways: [
      'Capacity factor measures how often a plant runs at full capacity',
      'Higher isn\'t always better - depends on grid needs',
      'Nuclear and geothermal have highest capacity factors (~90%)',
      'Renewables have lower CF but are getting better with technology',
      'Low CF can still be valuable if generation matches peak demand',
      'Grid needs a mix of high-CF baseload and flexible generation'
    ]
  }
};

// Helper function to get content by ID
export function getHelpContent(id: string): HelpContent | undefined {
  return HELP_CONTENT_DATABASE[id];
}

// Get all content IDs
export function getAllHelpContentIds(): string[] {
  return Object.keys(HELP_CONTENT_DATABASE);
}

// Search help content
export function searchHelpContent(query: string): HelpContent[] {
  const lowerQuery = query.toLowerCase();
  return Object.values(HELP_CONTENT_DATABASE).filter(
    (content) =>
      content.title.toLowerCase().includes(lowerQuery) ||
      content.category?.toLowerCase().includes(lowerQuery) ||
      Object.values(content.explanations).some((explanation) =>
        explanation.toLowerCase().includes(lowerQuery)
      )
  );
}

export default HELP_CONTENT_DATABASE;
