/**
 * Help Content Database
 *
 * Pre-written explanations for all major concepts in the dashboard
 * with 3-level explanations (Beginner, Intermediate, Expert)
 */

import { HelpContent } from '../components/education/SmartHelpPanel';

export const HELP_CONTENT_DATABASE: Record<string, HelpContent> = {
  'energy-mix': {
    id: 'energy-mix',
    title: 'Energy Mix',
    category: 'Basics',
    explanations: {
      beginner: `Energy Mix shows where our electricity comes from! Think of it like a recipe - instead of ingredients like flour and sugar, we use different "ingredients" to make electricity:

🌬️ Wind turbines (using wind)
☀️ Solar panels (using sunlight)
💧 Hydro dams (using flowing water)
⚡ Natural gas plants (burning gas)
⚛️ Nuclear plants (splitting atoms)

Just like a recipe, the mix changes throughout the day! At night, we can't use solar, so we use more of the other sources. A good energy mix uses lots of clean, renewable sources like wind and solar!`,

      intermediate: `The Energy Mix represents the proportion of electricity generated by different sources in real-time. It's measured in:

• Megawatts (MW) - How much power right now
• Percentage (%) - What share of total generation

Key types of energy sources:
🟢 Renewables (Clean): Wind, Solar, Hydro - Don't run out, low carbon
🟡 Fossil Fuels: Natural Gas, Coal - Limited supply, high carbon
🔵 Nuclear: Uranium - Clean but creates waste

A balanced mix considers:
- Reliability (baseload vs. intermittent)
- Cost ($/MWh)
- Environmental impact (CO2 emissions)
- Energy security (domestic vs. imported)`,

      expert: `Energy Mix Analysis provides real-time generation capacity data from grid operators (AESO, IESO, BC Hydro) via API integration:

Technical Breakdown:
• Baseload: Nuclear (90%+ capacity factor), Run-of-river Hydro
• Load Following: Natural Gas Combined Cycle, Hydro Storage
• Peaking: Gas Turbines, Battery Storage
• Variable Renewable: Wind (35% CF), Solar (25% CF)

Grid Dispatch Stack:
1. Must-run generators (nuclear, renewables)
2. Economic dispatch order by marginal cost
3. Ancillary services (frequency regulation, reserves)
4. Curtailment during low demand

Key Metrics:
- Capacity Factor = Actual Generation / Nameplate Capacity
- Emissions Intensity = gCO2/kWh (varies by source)
- LCOE (Levelized Cost) = Total lifecycle cost / Total energy
- Grid Stability = Frequency variance, voltage control

Integration challenges with high renewable penetration:
- Duck curve (California) - Evening ramp-up challenges
- Grid inertia reduction - Requires synthetic inertia or storage
- Transmission constraints - Regional interconnection limits`
    },
    realWorldExample: `Imagine your home in the evening. When you turn on lights, TV, and start cooking dinner, you're part of the "peak demand" time (5-9 PM).

During this time, Alberta might use:
- 60% Natural Gas (reliable, quick to turn on/off)
- 20% Wind (if it's windy!)
- 15% Coal (being phased out)
- 5% Other sources

But at 2 AM when everyone's asleep? Demand drops 40%, so we use fewer power plants. This is why understanding the mix helps - we can plan when to charge electric cars or run dishwashers to use cheaper, cleaner electricity!`,
    funFact: `🌟 Did you know? On a really windy day in Alberta, wind turbines can generate enough power for over 1 million homes! That's like powering the entire cities of Calgary and Edmonton combined - just from wind!`,
    keyTakeaways: [
      'Energy mix changes throughout the day based on demand',
      'Renewable sources (wind, solar, hydro) are clean but variable',
      'A diverse mix ensures reliability and lower costs',
      'Canada is moving toward more renewable energy to fight climate change'
    ],
    relatedConcepts: [
      { id: 'renewable-energy', title: 'What is Renewable Energy?' },
      { id: 'grid-stability', title: 'How the Power Grid Works' },
      { id: 'capacity-factor', title: 'Understanding Capacity Factor' },
      { id: 'carbon-emissions', title: 'Carbon Emissions from Energy' }
    ]
  },

  'renewable-energy': {
    id: 'renewable-energy',
    title: 'Renewable Energy',
    category: 'Clean Energy',
    explanations: {
      beginner: `Renewable energy comes from sources that never run out! Unlike coal or oil that will eventually be used up, renewable sources keep coming back naturally.

The main types are:

🌬️ **Wind** - Giant turbines spin in the wind, like huge pinwheels
☀️ **Solar** - Panels capture sunlight and turn it into electricity
💧 **Hydro** - Water flowing through dams spins turbines
🌊 **Tidal** - Ocean waves and tides generate power
🌋 **Geothermal** - Heat from inside Earth

Why they're awesome:
✅ Never run out
✅ Don't pollute the air
✅ Help fight climate change
✅ Create jobs
✅ Costs keep going down`,

      intermediate: `Renewable energy sources generate electricity without depleting natural resources or producing significant greenhouse gas emissions during operation.

**Key Characteristics:**
- Naturally Replenishing: Source regenerates on human timescales
- Low Carbon: Minimal CO2 emissions during operation
- Variable Output: Most depend on weather conditions (except hydro/geothermal)
- Decreasing Costs: Technology improvements driving price down

**Economics:**
- Wind: $30-60/MWh (cheapest new generation)
- Solar: $30-50/MWh (falling rapidly)
- Hydro: $40-100/MWh (established, location-dependent)
- For comparison: Gas $40-80/MWh, Coal $60-140/MWh

**Challenges:**
- Intermittency: Need backup power or storage
- Grid Integration: Requires flexible, smart grid infrastructure
- Location-Specific: Best resources aren't always near cities
- Upfront Costs: High capital expense, low operating costs`,

      expert: `Renewable Energy Systems (RES) encompass non-depleting, low-emission generation technologies with distinct technical characteristics:

**Resource Assessment:**
- Wind: Weibull distribution analysis, capacity factor 25-45% (offshore 35-50%)
- Solar PV: Global Horizontal Irradiance (GHI), Performance Ratio typically 75-85%
- Hydro: Run-of-river (CF 40-70%) vs. Storage (CF 40-60%, flexible dispatch)
- Geothermal: Baseload (CF 85-95%), binary cycle for low-temp resources

**Grid Integration Technical Challenges:**

1. Variability & Uncertainty:
   - Sub-hourly forecasting (machine learning, ensemble methods)
   - Probabilistic dispatch optimization
   - Reserve requirement increases (regulation, load following)

2. Reduced System Inertia:
   - Grid-forming inverters (GFM) vs. grid-following (GFL)
   - Synthetic inertia from battery storage or wind turbines
   - Fast frequency response (FFR) ancillary services

3. Transmission & Distribution:
   - Power flow reversal in distribution networks
   - Voltage control with high DER penetration
   - Reactive power management (Q-V droop control)

**Energy Storage Integration:**
- Li-ion batteries: 4-6 hour duration, rapid response (<100ms)
- Pumped hydro: 8-24+ hours, bulk storage
- Green hydrogen: Seasonal storage, sector coupling

**Market & Policy Mechanisms:**
- Feed-in Tariffs (FIT) vs. Renewable Portfolio Standards (RPS)
- Renewable Energy Certificates (RECs) / Carbon Credits
- Capacity markets with technology-neutral auctions
- Net metering and time-of-use rates

**LCOE Calculation:**
LCOE = (Capital Cost + O&M + Financing) / Lifetime Energy Production
- Consider: capacity factor, degradation, financing terms
- Competing with "Energy Value" not just cost
- System LCOE includes integration costs`
    },
    realWorldExample: `Let's look at a real Canadian community: Summerside, Prince Edward Island.

This town of 16,000 people gets 100% of its electricity from renewable sources! They use:
- Wind turbines on nearby farms
- Solar panels on municipal buildings
- Battery storage to balance supply

Result?
✅ Electricity bills down 10-20%
✅ No more power outages from storms (battery backup)
✅ Created 300 local jobs
✅ Reduced emissions by 40,000 tonnes/year (like removing 8,000 cars)

What started as an expensive experiment is now saving money AND the environment!`,
    funFact: `🚀 In 2023, renewables became the CHEAPEST form of new electricity generation in history! Solar and wind are now cheaper than coal and gas, even without subsidies. That's why investors are pouring money into clean energy - it's good for the planet AND their wallets!`,
    keyTakeaways: [
      'Renewable energy is now the cheapest form of new power generation',
      'Main challenge is intermittency (wind doesn\'t always blow, sun doesn\'t always shine)',
      'Battery storage is solving the intermittency problem',
      'Canada has incredible renewable resources: hydro, wind, solar, geothermal',
      'Transitioning to renewables creates jobs and reduces pollution'
    ],
    relatedConcepts: [
      { id: 'energy-storage', title: 'Energy Storage & Batteries' },
      { id: 'smart-grid', title: 'Smart Grid Technology' },
      { id: 'carbon-emissions', title: 'Reducing Carbon Emissions' },
      { id: 'energy-costs', title: 'Cost of Different Energy Sources' }
    ]
  },

  'carbon-emissions': {
    id: 'carbon-emissions',
    title: 'Carbon Emissions',
    category: 'Environment',
    explanations: {
      beginner: `Carbon emissions are like "invisible smoke" that comes from burning fossil fuels (coal, oil, natural gas) to make electricity, drive cars, or heat homes.

🏭 Why it matters:
Carbon dioxide (CO2) traps heat in Earth's atmosphere like a blanket, making the planet warmer. This causes:
- Hotter summers
- Melting ice caps
- Rising sea levels
- More extreme weather

🌱 How we measure it:
- Tons of CO2 per year
- Grams of CO2 per kilowatt-hour of electricity

Different energy sources produce different amounts:
🔴 Coal: LOTS of carbon (most polluting)
🟡 Natural Gas: Medium carbon
🟢 Wind/Solar/Hydro: ZERO carbon (clean!)

🎯 The Goal:
Reduce carbon emissions to "Net Zero" by 2050 to stop climate change!`,

      intermediate: `Carbon emissions from electricity generation are measured in grams of CO2 equivalent per kilowatt-hour (gCO2e/kWh). This includes:

**Emission Intensities by Source:**
☠️ Coal: 820-950 gCO2/kWh (worst)
🟡 Natural Gas: 350-490 gCO2/kWh
🔵 Nuclear: 12-15 gCO2/kWh (lifecycle emissions)
🟢 Wind: 11-12 gCO2/kWh
🟢 Solar: 40-50 gCO2/kWh
🟢 Hydro: 24-30 gCO2/kWh

**Why It Varies:**
- Fuel quality (e.g., anthracite vs. lignite coal)
- Plant efficiency (modern CCGT vs. old gas plants)
- Manufacturing emissions (solar panel production)
- Lifecycle analysis (construction, operation, decommissioning)

**Carbon Pricing:**
Canada's carbon tax: $80/tonne CO2 (2024), rising to $170/tonne (2030)
- Makes fossil fuels more expensive
- Incentivizes clean energy
- Rebates to households

**Personal Carbon Footprint:**
Average Canadian: 15 tonnes CO2/year
- Electricity: ~2 tonnes
- Transportation: ~5 tonnes
- Heating: ~3 tonnes
- Everything else: ~5 tonnes`,

      expert: `Carbon Intensity Analysis for Power Systems:

**Emission Accounting Methodologies:**

1. **Direct Emissions (Scope 1):**
   - Combustion: C_emissions = Fuel_burned × Emission_factor × (1 - capture_rate)
   - Natural Gas CCGT: 350-400 gCO2/kWh (50-60% thermal efficiency)
   - Subcritical Coal: 900-1000 gCO2/kWh (33-38% efficiency)
   - Supercritical Coal: 750-850 gCO2/kWh (40-45% efficiency)

2. **Lifecycle Emissions (Scope 1-3):**
   - Includes: Manufacturing, construction, O&M, fuel extraction, decommissioning
   - IPCC Lifecycle Assessment values:
     - Wind: 11 gCO2e/kWh (steel, concrete in turbine/foundation)
     - Solar PV: 40-50 gCO2e/kWh (silicon purification, panel production)
     - Nuclear: 12 gCO2e/kWh (enrichment, construction, waste management)
     - Hydro: 24 gCO2e/kWh (reservoir methane in some cases)

**Grid Carbon Intensity Calculation:**

Marginal Emission Rate = dEmissions/dDemand
Average Emission Rate = Total Emissions / Total Generation

- Marginal rate determines impact of load changes
- Important for EV charging optimization, demand response

**Carbon Capture Utilization & Storage (CCUS):**
- Post-combustion capture: 85-90% capture rate, 15-25% energy penalty
- Pre-combustion (IGCC): 90-95% capture, better efficiency
- Oxy-fuel combustion: 90%+ capture, requires oxygen separation
- Storage: Geological sequestration, enhanced oil recovery (EOR)
- Cost: $50-100/tonne CO2 captured (decreasing)

**Decarbonization Pathways:**

1. **Supply-Side:**
   - Renewable generation build-out (70-85% of mix)
   - Nuclear baseload (10-20%)
   - CCS for remaining fossil (5-10%)
   - Green hydrogen for storage/backup

2. **Demand-Side:**
   - Electrification (transport, heating)
   - Energy efficiency improvements
   - Demand response / flexible loads
   - Behavioral changes

**Carbon Pricing Economics:**
- Social Cost of Carbon: $50-200/tonne (wide range, discount rate dependent)
- Carbon tax vs. Cap-and-Trade tradeoffs
- Border Carbon Adjustments (BCAs) to prevent leakage
- Revenue recycling: Dividends vs. investment in clean tech

**Net-Zero Targets:**
- Canada: 2050 net-zero legislation
- Interim targets: 40-45% below 2005 levels by 2030
- Electricity grid: 100% zero-emission by 2035
- Residual emissions offset with negative emission technologies (NET):
  - Direct Air Capture (DAC): $100-600/tonne
  - Bioenergy with CCS (BECCS)
  - Afforestation/reforestation`
    },
    realWorldExample: `Let's compare two provinces:

**Alberta (High Carbon):**
- 90% electricity from fossil fuels (mostly coal & gas)
- Grid carbon intensity: ~600 gCO2/kWh
- Average household: 10,000 kWh/year = 6 tonnes CO2
- Like driving a gas car 24,000 km

**Quebec (Low Carbon):**
- 95% electricity from hydro
- Grid carbon intensity: ~30 gCO2/kWh
- Same household: 10,000 kWh/year = 0.3 tonnes CO2
- 20x cleaner than Alberta!

**Your Impact:**
If an Alberta family switched to an electric car:
- Save: 3 tonnes CO2/year
- BUT charging from coal/gas grid adds 2 tonnes
- Net benefit: 1 tonne/year

Same family in Quebec:
- Save: 3 tonnes CO2/year
- EV charging adds only 0.1 tonnes
- Net benefit: 2.9 tonnes/year

**This is why grid decarbonization matters so much!**`,
    funFact: `🌍 Mind-blowing fact: The entire internet and all data centers globally produce about 2% of world's carbon emissions - roughly the same as the aviation industry! That's why tech companies like Google and Microsoft are investing billions in renewable energy to power their servers.`,
    keyTakeaways: [
      'Carbon emissions from energy cause climate change',
      'Different energy sources have vastly different carbon intensities',
      'Coal is ~25x more polluting than renewable energy',
      'Canada is phasing out coal by 2030',
      'Personal actions matter: energy efficiency, EVs, clean energy choices',
      'Carbon pricing makes clean energy more economically competitive'
    ],
    relatedConcepts: [
      { id: 'renewable-energy', title: 'Renewable Energy' },
      { id: 'energy-mix', title: 'Energy Mix' },
      { id: 'climate-change', title: 'Climate Change Impacts' },
      { id: 'carbon-capture', title: 'Carbon Capture Technology' }
    ]
  },

  // Add more content entries as needed...
  'capacity-factor': {
    id: 'capacity-factor',
    title: 'Capacity Factor',
    category: 'Technical Metrics',
    explanations: {
      beginner: `Capacity Factor shows how often a power plant is actually running at full power.

Think of it like a store:
🏪 A 24/7 store that's always open = 100% capacity factor
🏪 A store open 12 hours/day = 50% capacity factor

For power plants:
⚛️ Nuclear: ~90% (runs almost all the time)
💧 Hydro: ~50% (depends on water flow)
🌬️ Wind: ~35% (only when it's windy)
☀️ Solar: ~25% (only during daytime, best when sunny)

Why it matters:
- Higher capacity = more reliable
- Lower capacity = need backup power
- Affects the cost per kWh
- Important for planning the grid`,

      intermediate: `Capacity Factor = (Actual Energy Generated / Maximum Possible Generation) × 100%

It measures how efficiently a power plant operates over a period (usually annually).

**Typical Values:**
- Nuclear: 85-95% (excellent baseload, planned maintenance only)
- Coal: 40-70% (economic dispatch, being phased out)
- Natural Gas CCGT: 40-65% (flexible, used for load following)
- Hydro (storage): 40-60% (seasonal variations, drought impacts)
- Onshore Wind: 30-45% (best sites in Alberta, Saskatchewan)
- Offshore Wind: 40-55% (steadier ocean winds)
- Solar PV: 15-30% (latitude dependent, weather variations)
- Geothermal: 85-95% (baseload, very reliable)

**Why Low Capacity Factors Aren't Always Bad:**
- Peaker plants (gas turbines): 5-20% CF, but essential for reliability
- Solar might be 20% CF but generates during peak demand (valuable!)
- Cost per kWh matters more than CF alone

**Impact on Economics:**
LCOE = (Capital + O&M) / (Capacity × CF × Lifetime)
Lower CF = Higher LCOE (more expensive per kWh)`,

      expert: `Capacity Factor Analysis & Grid Planning:

**Mathematical Definition:**
CF = E_actual / (P_nameplate × 8760 hours) × 100%

Where:
- E_actual = Annual energy generation (MWh)
- P_nameplate = Rated capacity (MW)
- 8760 = hours in a year (365 days × 24 hours)

**Factors Affecting Capacity Factor:**

1. **Resource Availability:**
   - Wind: Weibull distribution, power curve, wake effects
   - Solar: Solar irradiance (GHI/DNI), temperature coefficient
   - Hydro: Inflow variability, reservoir management strategy

2. **Technical Limitations:**
   - Forced outage rate (FOR): Unplanned shutdowns
   - Planned outage rate (POR): Scheduled maintenance
   - Deration: Partial output due to fouling, aging
   - Curtailment: Grid operator constraints, negative pricing

3. **Economic Dispatch:**
   - Merit order: Marginal cost determines dispatch priority
   - Gas plants: Flexible, run when economical
   - Coal: Ramping constraints, minimum stable output

**Advanced Metrics:**

1. **Equivalent Availability Factor (EAF):**
   EAF = (Available Hours - Equivalent Outage Hours) / Total Hours
   - Better indicator of reliability than CF
   - Accounts for partial outages

2. **Equivalent Forced Outage Rate (EFOR):**
   EFOR = (Forced Outage Hours + Equivalent Forced Derated Hours) / Service Hours
   - Key metric for baseload plants
   - Industry benchmark: Nuclear <5%, Fossil 5-10%

3. **Net Capacity Factor:**
   Accounts for parasitic load (station use, auxiliary power)
   - Important for CCUS plants (energy penalty for capture)

**Grid Planning Implications:**

1. **Resource Adequacy:**
   - Effective Load Carrying Capacity (ELCC) of variable renewables
   - ELCC_wind ≈ 10-20% of nameplate (contribution to peak)
   - ELCC_solar ≈ 40-70% (better correlation with peak demand)

2. **Capacity Credit:**
   Credit = ELCC / Nameplate Capacity
   - Used in capacity markets
   - Reflects reliability contribution, not energy

3. **Intermittency Management:**
   - Variability: Short-term fluctuations (sub-hourly)
   - Uncertainty: Forecast error (day-ahead to real-time)
   - Geographic diversity reduces correlation
   - Hybrid plants (wind + solar + storage) improve CF

**Optimization Strategies:**

1. **Improving Wind CF:**
   - Taller towers: Access higher, steadier winds (+5-10% CF)
   - Larger rotors: Better low-wind performance
   - Advanced controls: Yaw optimization, wake steering

2. **Improving Solar CF:**
   - Single-axis trackers: +20-30% vs. fixed tilt
   - Bifacial modules: +10-20% from ground reflectance
   - Hybrid inverters: DC overbuilding (1.2-1.4x)

3. **Storage-Enhanced CF:**
   - Solar + battery: Shift generation to peak demand
   - "Firm" renewable profile (90%+ CF equivalent)
   - Increased capacity credit (70-90%)`
    },
    realWorldExample: `Let's visit the Darlington Nuclear Station in Ontario:

**The Numbers:**
- Capacity: 3,512 MW (4 reactors × 878 MW)
- Capacity Factor: 93% (2022)
- Hours in a year: 8,760

**Calculation:**
Maximum possible generation = 3,512 MW × 8,760 hours = 30.8 million MWh
Actual generation = 30.8 million × 0.93 = 28.6 million MWh

**What does 28.6 million MWh power?**
Average Ontario home uses 9,000 kWh/year
28.6 billion kWh ÷ 9,000 = 3.2 million homes!

That's nearly HALF of all homes in Ontario powered by just this one station, running 93% of the time!

**Why 93% and not 100%?**
- 3-4 weeks/year for refueling each reactor (staggered)
- Routine maintenance
- Safety inspections
- Still incredibly reliable!`,
    funFact: `⚡ The worst capacity factor ever? Germany's solar panels during January! They average just 5-8% capacity factor in winter (short days, cloudy weather). But in summer? They jump to 30-35%! This is why energy storage and diverse renewable sources are so important - you can't rely on just one technology.`,
    keyTakeaways: [
      'Capacity factor measures how often a plant runs at full capacity',
      'Higher isn\'t always better - depends on grid needs',
      'Nuclear and geothermal have highest capacity factors (~90%)',
      'Renewables have lower CF but are getting better with technology',
      'Low CF can still be valuable if generation matches peak demand',
      'Grid needs a mix of high-CF baseload and flexible generation'
    ]
  },

  //
  // ========== NEW HELP TOPICS ==========
  //

  'ai-datacentre-energy': {
    id: 'ai-datacentre-energy',
    title: 'AI Data Centres & Energy',
    category: 'Clean Technology',
    explanations: {
      beginner: `AI Data Centres are like giant computer buildings that run artificial intelligence! Think of them as huge brain warehouses where:

🖥️ **What they do:**
- Run ChatGPT, Google Search, Netflix recommendations
- Process millions of calculations per second
- Store and analyze massive amounts of data

⚡ **Why they use SO MUCH energy:**
- Thousands of powerful computers running 24/7
- Need cooling (like air conditioning) to prevent overheating
- A large AI data center uses as much power as a small city!

Think of it like this: Your laptop gets warm when you use it for a while. Now imagine 10,000 laptops running at full speed all day, every day - that's a data center!`,

      intermediate: `AI Data Centres house the computing infrastructure for artificial intelligence applications, consuming significant energy for:

**Power Breakdown:**
- Computing (GPUs/TPUs): 60-70% of total energy
- Cooling systems: 25-35%
- Networking & storage: 5-10%

**Why AI Uses More Energy:**
- Training large language models (LLMs) requires massive computation
- Deep learning = billions of mathematical operations
- GPUs (graphics processors) are 100x more power-hungry than regular CPUs
- 24/7 operation with no downtime

**Energy Intensity:**
- Traditional data center: 100-200 W per square foot
- AI data center: 250-400 W per square foot (2-4x higher!)
- Training GPT-3: ~1,300 MWh (enough to power 120 homes for a year)

**Power Usage Effectiveness (PUE):**
- Best practice: PUE of 1.1-1.2 (only 10-20% wasted on cooling)
- Industry average: PUE of 1.5 (50% extra for cooling)`,

      expert: `AI Data Centres present unique energy challenges due to high-density computing and thermal management requirements:

**Architecture & Power Density:**
- GPU-accelerated compute: NVIDIA H100 (700W TDP), AMD MI300X (750W)
- Rack density: 30-50 kW/rack (vs. 5-10 kW traditional)
- Hot aisle containment, liquid cooling increasingly necessary
- Facility total load: 10-100+ MW per facility

**PUE Optimization Strategies:**
PUE = Total Facility Power / IT Equipment Power

1. **Advanced Cooling:**
   - Direct-to-chip liquid cooling (COP 30-40 vs. 3-5 air)
   - Free cooling (economizers): Ambient when T < 18°C
   - Adiabatic cooling, evaporative systems
   - Immersion cooling for ultra-high density

2. **Power Infrastructure:**
   - 480V DC distribution (3-5% efficiency gain)
   - On-site generation: Natural gas turbines, fuel cells
   - Energy storage for demand response
   - Grid-interactive UPS systems

**AI Workload Characteristics:**
- Training: Predictable, schedulable, batch processing
  → Can shift to low-cost / high-renewable periods
- Inference: Latency-sensitive, real-time demand
  → Requires continuous availability

**Carbon Impact:**
- Model training carbon footprint varies by:
  - Hardware efficiency (FLOPS/Watt)
  - Grid carbon intensity (location-dependent)
  - Training duration & model size
- GPT-3 training: ~500 tonnes CO2e (using average US grid)
- Strategies: Green PPAs, carbon-aware workload scheduling

**Demand Response & Grid Integration:**
- AI training workloads are flexible → ideal for DR programs
- Curtailment during grid stress events
- Potential for providing ancillary services (frequency regulation)
- Challenges: Cooling thermal inertia limits rapid power changes`
    },
    realWorldExample: `**Microsoft's Quebec AI Data Center:**

Microsoft built a massive AI data center in Quebec specifically because:
1. **99% hydro power** - Nearly carbon-free electricity
2. **Cold climate** - Free cooling 8+ months/year
3. **Low electricity costs** - $0.05/kWh (vs $0.12 US average)

**The Numbers:**
- Power consumption: 50 MW (enough for 40,000 homes)
- PUE achieved: 1.12 (vs. 1.6 industry average)
- Carbon savings: 95% lower than coal-powered equivalent
- Annual CO2 avoided: ~200,000 tonnes

Result? They can train AI models faster AND cheaper AND cleaner than almost anywhere else in the world!`,
    funFact: `🤯 Training ONE large AI model (like GPT-4) can use as much electricity as 120 Canadian homes consume in an entire year! That's why tech companies are racing to build data centers near hydroelectric dams in Quebec and Norway - for clean, cheap power.`,
    keyTakeaways: [
      'AI data centers use 2-4x more power than traditional data centers',
      'GPUs for AI training are extremely power-hungry (700W each)',
      'Cooling accounts for 25-35% of total energy use',
      'Location matters: Quebec hydro power = 95% lower carbon',
      'AI workloads are flexible and can be scheduled during low-cost periods',
      'Future: Liquid cooling and renewable energy integration critical'
    ],
    relatedConcepts: [
      { id: 'pue-metric', title: 'Power Usage Effectiveness (PUE)' },
      { id: 'renewable-energy', title: 'Renewable Energy' },
      { id: 'carbon-emissions', title: 'Carbon Emissions' }
    ]
  },

  'hydrogen-production': {
    id: 'hydrogen-production',
    title: 'Hydrogen Production Methods',
    category: 'Clean Technology',
    explanations: {
      beginner: `Hydrogen is like an invisible fuel that only creates water when it burns - no smoke or pollution! But we need to make it first.

**The 3 Colors of Hydrogen:**

💚 **Green Hydrogen** (Cleanest!)
- Made using renewable energy (wind, solar, hydro)
- Uses electricity to split water: H₂O → H₂ + O₂
- Zero carbon emissions!

🔵 **Blue Hydrogen** (Pretty Clean)
- Made from natural gas
- But captures the carbon (CCS technology)
- 90% fewer emissions than grey

⚫ **Grey Hydrogen** (Not Clean)
- Made from natural gas without capturing carbon
- Releases lots of CO₂
- Cheapest but dirtiest

Think of it like this: Green hydrogen is like growing your own vegetables (clean!), blue is like buying organic (better), and grey is like eating junk food (cheap but not good for you).`,

      intermediate: `Hydrogen production methods are categorized by carbon intensity:

**Green Hydrogen (Electrolysis):**
Water + Renewable Electricity → Hydrogen + Oxygen
- Process: H₂O + electricity → 2H₂ + O₂
- Energy required: 50-55 kWh per kg H₂
- Cost: $4-7/kg (2024, falling rapidly)
- Emissions: 0-1 kg CO₂/kg H₂

**Blue Hydrogen (SMR + CCS):**
Natural Gas + Steam → Hydrogen + CO₂ (captured)
- CH₄ + H₂O → CO + 3H₂ → 4H₂ + CO₂
- 85-95% carbon capture rate
- Cost: $2-3/kg
- Emissions: 1-3 kg CO₂/kg H₂

**Grey Hydrogen (SMR):**
Natural Gas + Steam → Hydrogen (CO₂ vented)
- No carbon capture
- Cost: $1-2/kg (cheapest)
- Emissions: 10-12 kg CO₂/kg H₂

**Emerging Technologies:**
- **Turquoise:** Methane pyrolysis (solid carbon output)
- **Pink:** Nuclear-powered electrolysis
- **Yellow:** Grid-powered electrolysis (mixed sources)

**Key Metric: LCOH (Levelized Cost of Hydrogen)**
Green H₂ becoming competitive with blue/grey by 2030 in many regions`,

      expert: `Hydrogen Production Pathways & Techno-Economics:

**1. Alkaline Electrolysis (AEL):**
- Technology: Liquid KOH electrolyte, Ni-based electrodes
- Efficiency: 60-70% (HHV), 50-60 kWh/kg H₂
- Capex: $500-1,000/kW (declining)
- Advantages: Mature, proven, 60K+ hours lifetime
- Disadvantages: Slow startup, limited partial load operation
- Best for: Baseload renewable integration (hydro, geothermal)

**2. Proton Exchange Membrane (PEM) Electrolysis:**
- Technology: Solid polymer electrolyte, Pt/Ir catalysts
- Efficiency: 65-75% (HHV), 48-52 kWh/kg H₂
- Capex: $1,000-1,800/kW
- Advantages: Fast response (<1s), high current density, compact
- Disadvantages: Expensive catalysts, acidic environment
- Best for: Variable renewable integration (wind, solar)

**3. Solid Oxide Electrolysis (SOEC):**
- Technology: High-temperature (700-900°C) ceramic electrolyte
- Efficiency: 80-90% (HHV) with waste heat integration
- Capex: $1,500-2,500/kW (early stage)
- Advantages: Highest efficiency, can run in reverse (fuel cell)
- Disadvantages: Thermal cycling limits, early commercial stage
- Best for: Industrial integration with waste heat

**4. Steam Methane Reforming (SMR) + CCS:**
- Reaction: CH₄ + H₂O ⇌ CO + 3H₂ (endothermic, 700-1,000°C)
            CO + H₂O ⇌ CO₂ + H₂ (water-gas shift)
- Capture: Post-combustion amine scrubbing (85-95% capture)
- Economics: $1.5-2.5/kg with CCS (depending on gas price, CCS cost)
- Challenge: Residual emissions (10-15%), methane leakage

**5. Autothermal Reforming (ATR) + CCS:**
- Partial oxidation + SMR hybrid
- Advantages: Higher CO₂ concentration (easier capture), modular
- 95%+ capture possible
- Emerging as preferred "blue" pathway

**LCOH Calculation:**
LCOH = (CAPEX × CRF + OPEX_fixed) / Annual_Production + Electricity_Cost × Consumption + Feedstock_Cost

Variables:
- Electrolyzer CAPEX: $500-1,800/kW (technology dependent)
- Capacity factor: 20-95% (depends on renewable availability)
- Electricity cost: $20-60/MWh (critical driver for green H₂)
- Stack replacement: Every 60,000-100,000 hours

**Green Hydrogen Cost Competitiveness:**
- By 2030: $2-3/kg in regions with cheap renewables
- Parity with blue hydrogen when:
  - Renewable electricity <$25/MWh AND
  - Electrolyzer CAPEX <$500/kW AND
  - Capacity factor >60%

**Policy Support:**
- US: IRA $3/kg production tax credit (clean H₂)
- EU: €10B Hydrogen Bank, RFNBO mandates
- Canada: Investment tax credits, Clean Fuel Regulations

**Infrastructure Challenges:**
- Hydrogen embrittlement in steel pipelines
- Compression (350-700 bar) energy penalty (10-15% of energy content)
- Storage: Geological (salt caverns), liquid (–253°C), metal hydrides
- Transportation: Pipelines (dedicated or blended), trucks, ships (ammonia carrier)`
    },
    realWorldExample: `**Air Products' Net-Zero Hydrogen Energy Complex (Alberta):**

The world's largest net-zero hydrogen production facility (2024):

**Project Specs:**
- Production: 1,500 tonnes/day of blue hydrogen
- Feedstock: Natural gas from Alberta
- CCS: 95% carbon capture → geological storage
- CO₂ sequestered: 3 million tonnes/year (equal to 650,000 cars)
- Cost: $1.6 billion CAD

**Why Alberta?**
1. Abundant natural gas supply
2. Existing CCS infrastructure (oil sands experience)
3. Hydrogen refining expertise
4. Proximity to US hydrogen demand

**Output Uses:**
- Industrial ammonia production
- Oil refinery upgrading (replacing grey H₂)
- Future: Hydrogen fuel for trucks/buses

This is Canada's bet on "blue before green" - using natural gas wealth to kickstart the hydrogen economy while green becomes affordable.`,
    funFact: `🚀 The Space Shuttle used 500,000 liters of liquid hydrogen per launch! Hydrogen has 3x the energy per kilogram as jet fuel, which is why NASA loves it. The only emission? Pure water vapor - astronauts could literally drink the exhaust!`,
    keyTakeaways: [
      'Green hydrogen (renewable powered) is carbon-free but currently expensive',
      'Blue hydrogen (gas + CCS) is 90% cleaner than grey, bridging to green',
      'Grey hydrogen (no capture) accounts for 95% of today\'s production',
      'Cost of green H₂ falling 50% by 2030 due to cheaper electrolyzers and renewables',
      'Canada is investing heavily in both blue (Alberta) and green (Quebec) hydrogen',
      'Hydrogen can store energy long-term, unlike batteries'
    ],
    relatedConcepts: [
      { id: 'energy-storage', title: 'Energy Storage' },
      { id: 'carbon-capture', title: 'Carbon Capture (CCS)' },
      { id: 'renewable-energy', title: 'Renewable Energy' }
    ]
  },

  'ev-charging-levels': {
    id: 'ev-charging-levels',
    title: 'EV Charging Levels',
    category: 'Clean Technology',
    explanations: {
      beginner: `Electric Vehicle (EV) charging is like filling up with gas, but with electricity! There are 3 speeds:

🐢 **Level 1 (Slow - Home outlet)**
- Uses regular wall outlet (like your phone charger)
- Speed: Adds 5-8 km of range per hour
- Time for full charge: 20-40 hours
- Best for: Overnight charging at home

🚗 **Level 2 (Medium - Home/Public)**
- Needs special 240V outlet (like an oven or dryer)
- Speed: Adds 25-40 km per hour
- Time for full charge: 4-8 hours
- Best for: Home garage, workplace, shopping centers

⚡ **Level 3 (Fast - DC Fast Charging)**
- Special high-power stations
- Speed: Adds 200-300 km in 30 minutes
- Time for 80% charge: 20-45 minutes
- Best for: Road trips, highway stops

Think of it like this:
- Level 1 = Filling a bathtub with a garden hose
- Level 2 = Filling with a kitchen faucet
- Level 3 = Filling with a fire hose!`,

      intermediate: `EV Charging is categorized by power delivery and charging speed:

**Level 1 (120V AC, 1.4-1.9 kW):**
- Standard household outlet
- Current: 12-16 amps
- Range added: 5-8 km/hour (3-5 mi/hr)
- Charging efficiency: 85-90%
- Cost: $0 (outlet already exists)
- Use case: Emergency/trickle charging

**Level 2 (208-240V AC, 3.3-19.2 kW):**
- Residential: 7.2 kW typical (30A @ 240V)
- Public: 11-19.2 kW (up to 80A @ 240V)
- Range added: 20-40 km/hour
- Charging efficiency: 85-92%
- Equipment cost: $500-2,000 installed
- Networks: ChargePoint, FLO, Tesla Destination

**Level 3 / DC Fast Charging (50-350+ kW):**
- **CCS (Combined Charging System):** 50-350 kW
  - Used by: Most non-Tesla EVs (GM, Ford, VW, etc.)
- **Tesla Supercharger:** 150-250 kW (V3), 250+ kW (V4)
  - Proprietary (but opening to others with adapter)
- **CHAdeMO:** 50-100 kW
  - Used by: Nissan Leaf, older EVs

**Charging Curves:**
- Fast charging rate decreases at high state of charge (SoC)
- Typically charges to 80% quickly, then slows (protects battery)
- 0-80%: 20-45 minutes
- 80-100%: Additional 30-60 minutes (inefficient)

**Grid Impact:**
- Level 1: <2 kW → negligible
- Level 2: 7 kW → equivalent to electric water heater
- DC Fast: 150 kW → significant demand charge implications`,

      expert: `EV Charging Infrastructure Technical Specifications & Grid Integration:

**Power Electronics & Standards:**

1. **AC Level 2 (SAE J1772 / IEC 62196):**
   - Onboard Charger (OBC): 3.3-22 kW AC → DC conversion
   - Power Factor: >0.95 (grid-friendly)
   - Efficiency: 88-94% (heat losses in OBC)
   - Smart charging protocols: ISO 15118, OCPP 1.6/2.0.1
   - V2G capability: Bidirectional OBCs emerging (Nissan, Ford)

2. **DC Fast Charging (CCS, CHAdeMO, NACS):**
   - Off-board conversion: Grid AC → DC at station
   - Voltage range: 200-1,000V DC
   - Current: Up to 500A (CCS), 600A (NACS)
   - Efficiency: 92-96% (station-side conversion)
   - Thermal management: Liquid-cooled cables for 350+ kW

**Charging Power Progression:**
- CCS 1.0: 50 kW (2012)
- CCS 2.0: 150 kW (2017)
- CCS 3.0: 350 kW (2019, limited deployment)
- Megawatt Charging (MCS): 1,000+ kW for trucks (2024+)

**Battery Constraints on Charging Speed:**
- C-rate: Charging current / Battery capacity
  - 1C: 1-hour charge (e.g., 75 kWh battery at 75 kW)
  - 2C: 30-minute charge (150 kW)
  - 3C+: Battery thermal stress, degradation concerns

- Charging curve optimization:
  - Cold batteries: Pre-heating required (Tesla, others)
  - Hot batteries: Thermal throttling reduces charging speed
  - High SoC: Voltage limits reduce current acceptance

**Grid Integration Challenges:**

1. **Demand Charges:**
   - DC fast charging: 15-minute peak demand billing
   - $10-20/kW demand charge in some jurisdictions
   - Example: 350 kW peak × $15/kW = $5,250/month demand charge
   - Solution: On-site battery buffering to reduce peak

2. **Transformer Loading:**
   - Typical residential transformer: 25-100 kVA
   - 5-10 homes with Level 2 charging → potential overload
   - Distribution upgrades needed in high-EV-penetration areas

3. **Voltage Regulation:**
   - Large charging loads cause voltage drop
   - Distribution voltage regulators, capacitor banks required

**Smart Charging & Demand Response:**
- **Managed Charging:** Utility controls start time (TOU optimization)
- **V2G (Vehicle-to-Grid):**
  - Bidirectional power flow: EV ← → Grid
  - Frequency regulation (fast response, 0.25-2 Hz)
  - Peak shaving, renewable integration
  - Degradation concern: Additional cycles on battery

- **V2H/V2B (Vehicle-to-Home/Building):**
  - Backup power during outages
  - Ford F-150 Lightning: 9.6 kW export, 3-10 days home power
  - Cost offset: Arbitrage (charge off-peak, discharge on-peak)

**Economics & Business Models:**
- DCFC station CAPEX: $150K-300K per 150 kW dispenser
- Operating costs: Electricity, demand charges, maintenance
- Utilization challenge: <20% typical (highway corridors higher)
- Break-even: 10-15% utilization with demand charge mitigation
- Revenue models: Per-kWh, per-minute, membership, demand response

**Future Trends:**
- Wireless charging (inductive): 11-22 kW, 92% efficiency (2025+)
- Dynamic wireless (in-road charging): Demonstration projects
- Battery swapping: NIO (China) → 5 min swap vs. charging
- Ultra-fast: 500+ kW "5-minute charge" by 2030 (solid-state batteries)`
    },
    realWorldExample: `**Petro-Canada's Electric Highway (Trans-Canada):**

Canada's coast-to-coast EV fast charging network:

**Coverage:**
- 50+ DC fast charging stations
- Every 250 km along the Trans-Canada Highway
- From Victoria, BC to St. John's, NL

**Technology:**
- 200 kW DC fast chargers (CCS + CHAdeMO)
- Tesla adapters available
- Payment: Credit card, mobile app, RFID

**Real-World Performance:**
- Tesla Model 3: 0-80% in 25 minutes (adds 300 km range)
- Ford F-150 Lightning: 0-80% in 40 minutes (adds 200 km range)
- Cost: ~$15-25 for 80% charge (vs $60-80 for gas equivalent)

**Grid Integration:**
- On-site battery storage at select locations
- Solar canopy pilots (reduce grid demand)
- Load management during peak times

This infrastructure makes cross-country EV road trips practical for the first time in Canada!`,
    funFact: `⚡ The Porsche Taycan can charge at up to 270 kW! That's adding 100 km of range in just 5 minutes - faster than most people take to use the restroom at a highway rest stop. The future of "refueling" is here!`,
    keyTakeaways: [
      'Level 1 (120V): Slow, but works with any outlet - great for overnight',
      'Level 2 (240V): Sweet spot for home/work - full charge in 4-8 hours',
      'DC Fast (50-350 kW): Road trip ready - 80% charge in 20-45 minutes',
      'Charging slows above 80% to protect battery life',
      'Smart charging can save money by charging during off-peak hours',
      'Vehicle-to-Grid (V2G) lets EVs support the grid and earn money'
    ],
    relatedConcepts: [
      { id: 'grid-stability', title: 'Grid Stability' },
      { id: 'energy-storage', title: 'Energy Storage' },
      { id: 'peak-demand', title: 'Peak vs Off-Peak Demand' }
    ]
  }

  // Add more topics here (continuing to 24 total)
};

// Helper function to get content by ID
export function getHelpContent(id: string): HelpContent | undefined {
  return HELP_CONTENT_DATABASE[id];
}

// Get all content IDs
export function getAllHelpContentIds(): string[] {
  return Object.keys(HELP_CONTENT_DATABASE);
}

// Search help content
export function searchHelpContent(query: string): HelpContent[] {
  const lowerQuery = query.toLowerCase();
  return Object.values(HELP_CONTENT_DATABASE).filter(
    (content) =>
      content.title.toLowerCase().includes(lowerQuery) ||
      content.category?.toLowerCase().includes(lowerQuery) ||
      Object.values(content.explanations).some((explanation) =>
        explanation.toLowerCase().includes(lowerQuery)
      )
  );
}

export default HELP_CONTENT_DATABASE;
