-- Create table to archive LLM report payloads
create table if not exists public.llm_reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  endpoint text not null, -- e.g., 'transition-report', 'data-quality'
  dataset_path text not null,
  timeframe text,
  focus text,
  payload jsonb not null
);

-- Helpful indexes
create index if not exists llm_reports_created_at_idx on public.llm_reports (created_at desc);
create index if not exists llm_reports_endpoint_idx on public.llm_reports (endpoint);
create index if not exists llm_reports_dataset_idx on public.llm_reports (dataset_path);

-- Row Level Security (optional open read, restricted write)
alter table public.llm_reports enable row level security;

-- Allow reads to anon (adjust as needed)
create policy if not exists llm_reports_read_policy on public.llm_reports
  for select
  using (true);

-- Only service role can insert (edge function uses service key)
create policy if not exists llm_reports_insert_policy on public.llm_reports
  for insert
  to service_role
  with check (true);
